apiVersion: flow-v1
kind: Pipeline
spec:
  pipeline_type: BUILD
  id: 588
  event_type: pull
  trigger:
    enable: true
    source_branch: .*
    commit_message: build*
    pr_title: ^(?!\s*$).+
    modified_files: '*.java'
    pr_comment: build
    pr_label: ""
  arguments:
    parameters:
    - name: jira
      value: ""
      type: parameter
    - name: pr
      value: ""
      type: parameter
    - name: git_clone_ref
      value: master
      type: parameter
    - name: CHART_VERSION
      value: 1.0.4
      type: parameter
    artifacts: []
deployparams:
  env_type: ""
  env_name: ""
  env_id: 0
  cluster_context_id: 0
  registry_id: 31
  cluster_provider: ""
  deploystrategy: null
