apiVersion: flow-v1
kind: Pipeline
spec:
  pipeline_type: deploy
  id: 589
  event_type: merge
  trigger:
    enable: true
    source_branch: stage*
    commit_message: PreprodDeploy*
    pr_title: ^(?!\s*$).+
    modified_files: '*.yaml'
    pr_comment: ""
  arguments:
    parameters:
    - name: jira
      value: dsdf
      type: parameter
    - name: pr
      value: dgf
      type: parameter
    - name: FlowDcCandidates
      value: '[313]'
      type: deploy_candidate_image
    - name: Helm_Chart
      value: '[314]'
      type: deploy_candidate_chart
    - name: staticConfig
      value: default
      type: parameter
    artifacts: []
deployparams:
  env_type: preprod
  env_name: Fk-Preprod
  env_id: 35
  cluster_context_id: 853
  registry_id: 0
  cluster_provider: K8
  deploystrategy:
    name: Canary
    minreadyseconds: "10"
    progressdeadlineseconds: "600"
    prodservice: ""
    secondaryservice: ""
    maxunavailable: 20%
    maxsurge: "0"
    phases:
    - weight: "20"
      pause: ""
    previewreplicacount: ""
    autopromotionenabled: ""
    autopromotionseconds: ""
    scaledowndelayseconds: ""
