# https://confluence.fkinternal.com/display/ALM/ConfD+Integration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      fcp/appid: {{ .Values.appId }}
      fcp/zone: in-hyderabad-1
      fcp/group: {{ .Values.group }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        fcp/appid: {{ .Values.appId }}
        fcp/zone: in-hyderabad-1
        fcp/group: {{ .Values.group }}
      annotations:
        fcp.k8s.mtl/mtl-config-map: {{ .Values.name }}
        fcp.k8s.mtl/cosmos-statsd: enabled
        fcp.k8s.mtl/cosmos-tail: enabled
        checksum/config: {{ include (print $.Template.BasePath "/config-map-static.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: {{ .Values.name }}
          configMap:
            name: {{ .Values.name }}
      containers:
        {{ if eq .Values.image.k8HelmDemo.bucket "" }}
        - image: {{ .Values.image.k8HelmDemo.registry }}/{{ .Values.image.k8HelmDemo.repository }}:{{ .Values.image.k8HelmDemo.tag }}
        {{ else }}
        - image: {{ .Values.image.k8HelmDemo.registry }}/{{ .Values.image.k8HelmDemo.bucket }}/{{ .Values.image.k8HelmDemo.repository }}:{{ .Values.image.k8HelmDemo.tag }}
        {{ end }}
          name: {{ .Values.name }}
          ports:
            - containerPort: {{ .Values.containerPort}}
          securityContext:
            runAsUser: 0
          env:
            - name: SERVER_CONFIG
              value: {{ .Values.application.config.path }}
          volumeMounts:
            - name: {{ .Values.name }}
              mountPath: {{ .Values.application.config.path }}
              subPath: {{ .Values.name }}.properties
              readOnly: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "1"
